Repository zen-browser/desktop, pull requests merged in 2024-10, with the labels that each got.

#2309 Fix: Add functionality to move workspace to the end and disable reorder mode on panel close
  src/browser/base/content/zen-popupset.inc.xhtml
  src/browser/base/content/zen-styles/zen-workspaces.css
Labels: size:S

#2306 Added AppImage installation option to README
  README.md
Labels: Enhancement, size:S

#2331 Fix: Update gradient generator logic
  src/browser/base/content/zen-popupset.inc.xhtml
Labels: size:XS

#2333 Fix an issue where workspace size is 0 on non-expanded toolbar
  src/browser/base/content/zen-styles/zen-workspaces.css
Labels: Bug, size:XS
