Repository zen-browser/desktop, pull requests merged in 2024-11, with the labels that each got.

#2580 Fix: Broken release notes link
  README.md
Labels: Bug, size:XS

#2583 Feature: Essentials
  src/browser/app/profile/zen-browser.js
  src/browser/base/content/browser-places-js.patch
  src/browser/base/content/navigator-toolbox-inc-xhtml.patch
  src/browser/base/content/zen-assets.inc.xhtml
  src/browser/base/content/zen-assets.jar.inc.mn
  src/browser/base/content/zen-styles/zen-sidebar.css
  src/browser/base/content/zen-styles/zen-tabs/vertical-tabs.css
  src/browser/components/places/content/browserPlacesViews-js.patch
  src/browser/components/preferences/zen-settings.js
Labels: Feature, size:L, lgtm

#2599 feat: Include zen pinned tabs storage
  src/browser/base/content/ZenStartup.mjs
  src/browser/base/content/zen-assets.jar.inc.mn
  src/browser/base/content/zen-preloaded.inc.xhtml
Labels: Feature, size:XS

#2613 Fix: remove duplicate script import.
  src/browser/base/content/ZenStartup.mjs
  src/browser/base/content/zen-preloaded.inc.xhtml
Labels: Bug, size:XS

#2625 feat(ui): Add new "Pin Tab Globally" context menu option
  src/browser/themes/shared/zen-icons/icons.css
Labels: Feature, size:XS

#2644 Ensure that when adding an essential it is saved correctly in the database.
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
Labels: Enhancement, size:S, lgtm

#2656 Fix: Parse user context ID correctly when pinning tabs
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
Labels: Bug, size:XS, lgtm

#2665 Feature: Add new icons for essentials context items
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
  src/browser/themes/shared/zen-icons/essential-add.svg
  src/browser/themes/shared/zen-icons/essential-remove.svg
  src/browser/themes/shared/zen-icons/icons.css
Labels: Feature, size:M, lgtm

#2681 Fixed: custom colours doubling and colour dots not clearing
  src/browser/base/zen-components/ZenGradientGenerator.mjs
Labels: Bug, size:M, lgtm

#2505 Update mozconfig
  configs/linux/mozconfig
Labels: Enhancement, size:S

#2734 Update zen-decks.css to fix split view spacing
  src/browser/base/content/zen-styles/zen-decks.css
Labels: size:XS

#2716 Fix: Migrate pinned tabs from older Zen versions
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
Labels: Bug, size:M

#2757 🐷
  src/browser/base/content/zen-styles/zen-profile-dialog.css
Labels: size:XS

#2764 Implement (better) workspace switching via swipe gestures
  src/browser/base/zen-components/ZenWorkspaces.mjs
Labels: Feature, size:L

#2771 Add workspace navigation via mouse back/forward buttons
  src/browser/base/zen-components/ZenWorkspaces.mjs
Labels: Feature, size:M

#2773 Support URL to FAQ
  src/browser/app/profile/zen-browser.js
Labels: Feature, size:XS

#2823 Support URL to FAQ - 2nd Try 🐷
  src/browser/app/profile/zen-browser.js
Labels: size:XS

#2807 Fix Inconsistent cursors in split view resize mode
  src/browser/base/content/zen-styles/zen-decks.css
Labels: Bug, size:XS, lgtm

#2790 Fix: file manager not opening in many scenarios
  flatpak/io.github.zen_browser.zen.yml.template
Labels: Bug, size:XS, lgtm

#2828 Feature: Add workspace switching by horizontally scrolling sidebar
  src/browser/base/zen-components/ZenWorkspaces.mjs
Labels: Feature, size:S, lgtm

#2846 Fix zen-browser/desktop/issues/2252 (#2807)
  src/browser/base/content/zen-styles/zen-decks.css
Labels: size:XS

#2853 Fix: Pinned tab state and favicon handling
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
Labels: Improvement, size:L, lgtm

#2903 Fix: Prevent pins deletion from database on non explicit tab closes (window closing)
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
Labels: Improvement, size:M, lgtm

#2916 Fix inconsistent cursor when resizing P2
  src/browser/base/zen-components/ZenSidebarManager.mjs
  src/browser/base/zen-components/ZenViewSplitter.mjs
Labels: Bug, size:XS

#2908 Adds zen profile item on-click feedback
  src/browser/base/content/zen-styles/zen-profile-dialog.css
Labels: Enhancement, size:XS

#2904 Feature: Add reset to pinned URL button to pinned tabs
  src/browser/base/content/zen-styles/zen-tabs/vertical-tabs.css
  src/browser/components/tabbrowser/content/tab-js.patch
  src/browser/themes/shared/zen-icons/icons.css
Labels: Feature, size:L

#2984 #2767 [Flatpak] Failed to create shader cache (Permission denied)
  flatpak/io.github.zen_browser.zen.yml.template
Labels: Bug, size:XS

#2947 Feature: container specific Essentials
  src/browser/app/profile/zen-browser.js
  src/browser/base/zen-components/ZenWorkspaces.mjs
  src/browser/components/preferences/zen-settings.js
Labels: Feature, size:M, lgtm

#2899 Add a "Discussions" link to issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: Enhancement, size:XS

#2542 Update README.md for installing native package Linux
  README.md
Labels: Enhancement, size:XS, lgtm

#2889 chore: Update flatpak manifest runtime versions to 24.08
  flatpak/io.github.zen_browser.zen.yml.template
Labels: size:XS

#2879 Display Add to Essentials tab context menu item before Pin Tab
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
Labels: Enhancement, size:XS

#3042 Dev - Add _moveWindowButtons support for -moz-gtk-csd-reversed-placement
  src/browser/base/content/ZenCustomizableUI.sys.mjs
Labels: Enhancement, size:XS

#3033 Fix: Restore pinned tabs to their pinned URLs on startup if the option is checked
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
  src/browser/base/zen-components/ZenPinnedTabsStorage.mjs
Labels: Bug, size:S

#2924 Style: make the URL bar more rounded
  src/browser/base/content/zen-styles/zen-urlbar.css
Labels: Enhancement, size:S

#3108 Toolbar redesign
  src/browser/app/profile/zen-browser.js
  src/browser/base/content/ZenStartup.mjs
  src/browser/base/content/ZenUIManager.mjs
  src/browser/base/content/browser-box-inc-xhtml.patch
  src/browser/base/content/zen-assets.inc.xhtml
  src/browser/base/content/zen-assets.jar.inc.mn
  src/browser/base/content/zen-styles/zen-animations.css
  src/browser/base/content/zen-styles/zen-browser-container.css
  src/browser/base/content/zen-styles/zen-browser-ui.css
  src/browser/base/content/zen-styles/zen-compact-mode.css
  src/browser/base/content/zen-styles/zen-cool-toolbar.css
  src/browser/base/content/zen-styles/zen-glance.css
  src/browser/base/content/zen-styles/zen-sidebar-panels.css
  src/browser/base/content/zen-styles/zen-tabs/vertical-tabs.css
  src/browser/base/content/zen-styles/zen-theme.css
  src/browser/base/content/zen-styles/zen-workspaces.css
  src/browser/base/content/zen-tabbrowser-elements.inc.xhtml
  src/browser/base/content/zenThemeModifier.js
  src/browser/base/zen-components/ZenGlanceManager.mjs
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
  src/browser/base/zen-components/ZenSidebarManager.mjs
  src/browser/base/zen-components/ZenThemesImporter.mjs
  src/browser/base/zen-components/ZenWorkspaces.mjs
  src/browser/base/zen-components/actors/ZenThemeMarketplaceChild.sys.mjs
Labels: size:L

#3111 refactor: update styling and structure of Zen UI components; remove d…
  src/browser/app/profile/zen-browser.js
  src/browser/base/content/ZenCustomizableUI.sys.mjs
  src/browser/base/content/ZenUIManager.mjs
  src/browser/base/content/zen-assets.inc.xhtml
  src/browser/base/content/zen-assets.jar.inc.mn
  src/browser/base/content/zen-styles/zen-browser-container.css
  src/browser/base/content/zen-styles/zen-browser-ui.css
  src/browser/base/content/zen-styles/zen-cool-toolbar.css
  src/browser/base/content/zen-styles/zen-glance.css
  src/browser/base/content/zen-styles/zen-tabs/vertical-tabs.css
  src/browser/base/content/zen-styles/zen-workspaces.css
  src/browser/components/customizableui/CustomizableUI-sys-mjs.patch
  src/browser/components/preferences/zen-settings.js
  src/browser/components/preferences/zenLooksAndFeel.inc.xhtml
  src/browser/themes/shared/tabbrowser/tabs-css.patch
Labels: size:XL

#3064 Fix: Correct sound tab icon overlay style
  src/browser/themes/shared/zen-icons/icons.css
Labels: size:XS, lgtm

#3113 (feat) Hide pinned tabs not in active workspace
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
Labels: size:XS
