Repository zen-browser/desktop, pull requests merged in 2025-07, with the labels that each got.

#9408 Fix incorrect tab count in closing confirmation dialog
  src/browser/components/BrowserGlue-sys-mjs.patch
Labels: Bug, size:S

#9428 add open button to background tab toast
  src/browser/themes/shared/zen-icons/icons.css
  src/zen/compact-mode/ZenCompactMode.mjs
Labels: Feature, size:S

#9690 New Crowdin updates
  locales/de/browser/browser/preferences/zen-preferences.ftl
  locales/fr/browser/browser/preferences/zen-preferences.ftl
  locales/fr/browser/browser/zen-general.ftl
  locales/fr/browser/browser/zen-welcome.ftl
  locales/fr/browser/browser/zen-workspaces.ftl
  locales/ga-IE/browser/browser/preferences/zen-preferences.ftl
  locales/nl/browser/browser/zen-folders.ftl
  locales/nl/browser/browser/zen-general.ftl
  locales/nl/browser/browser/zen-vertical-tabs.ftl
  locales/sv-SE/browser/browser/zen-general.ftl
Labels: size:M
