Repository zen-browser/desktop, pull requests merged in 2025-06, with the labels that each got.

#8783 refactor(ZenMods): rework how default values for mod preferences are set
  src/zen/mods/ZenMods.mjs
Labels: Improvement, size:M, lgtm

#8840 Removes repetition of a pre-existing function from the marketplace manager.
  src/browser/components/preferences/zen-settings.js
Labels: Improvement, size:S, lgtm

#8865 Clarify what to execute in newtab readme.
  src/browser/components/newtab/README.md
Labels: Improvement, size:XS, lgtm

#8963 Glance contextmenu search pref
  src/browser/app/profile/features/glance.inc
  src/zen/glance/ZenGlanceManager.mjs
Labels: Feature, size:XS, lgtm

#9016 Made the button in toasts stand out more like in arc
  src/zen/common/styles/zen-popup.css
Labels: Improvement, size:XS

#9018 Revert "Made the button in toasts stand out more like in arc"
  src/zen/common/styles/zen-popup.css
Labels: size:XS

#9116 Fix TypeError: can't access property "pinned", group is undefined
  src/zen/folders/ZenFolders.mjs
Labels: Bug, size:XS

#9210 docs: add local development setup guidelines
  docs/contribute.md
Labels: size:XS, lgtm

#9221 fix: align with Firefox UI styles & improve accessibility
  src/zen/common/styles/zen-theme.css
Labels: size:XS
