Repository zen-browser/desktop, pull requests merged in 2025-10, with the labels that each got.

#10654 chore: Re-enable updater service
  configs/windows/mozconfig
  src/browser/installer/package-manifest-in.patch
Labels: size:S

#10660 Revert "chore: Re-enable updater service"
  configs/windows/mozconfig
  src/browser/installer/package-manifest-in.patch
Labels: size:S

#10668 Revert "chore: Rollback from new folder animation until release"
  src/zen/folders/ZenFolder.mjs
Labels: size:S

#10670 New Crowdin updates
  locales/el/browser/browser/preferences/zen-preferences.ftl
  locales/ru/browser/browser/preferences/zen-preferences.ftl
  locales/ru/browser/browser/zen-folders.ftl
  locales/ru/browser/browser/zen-general.ftl
  locales/ru/browser/browser/zen-vertical-tabs.ftl
  locales/ru/browser/browser/zen-workspaces.ftl
Labels: size:M

#10690 chore: Refactor glance animtions
  build/flatpak/app.zen_browser.zen.yml.template
  locales/en-US/browser/browser/preferences/zen-preferences.ftl
  prefs/glance.yaml
  scripts/run_tests.py
  src/browser/components/preferences/zenLooksAndFeel.inc.xhtml
  src/zen/common/styles/zen-browser-container.css
  src/zen/glance/ZenGlanceManager.mjs
  src/zen/glance/actors/ZenGlanceChild.sys.mjs
  src/zen/glance/actors/ZenGlanceParent.sys.mjs
  src/zen/glance/zen-glance.css
  src/zen/split-view/ZenViewSplitter.mjs
  src/zen/tests/glance/browser.toml
  src/zen/tests/glance/browser_glance_close_select.js
  src/zen/tests/ignorePrefs.json
Labels: size:XXL

#10688 feat: Unload a workspace
  locales/en-US/browser/browser/zen-workspaces.ftl
  src/browser/base/content/zen-commands.inc.xhtml
  src/browser/base/content/zen-panels/popups.inc
  src/zen/common/zen-sets.js
  src/zen/workspaces/ZenWorkspaces.mjs
Labels: Feature, size:S, lgtm

#10735 feat: settings -> shortcuts: show conflicting shortcut label
  locales/en-US/browser/browser/preferences/zen-preferences.ftl
  src/browser/components/preferences/zen-settings.js
  src/zen/kbs/ZenKeyboardShortcuts.mjs
Labels: Feature, size:M, lgtm
