Repository zen-browser/desktop, pull requests merged in 2025-01, with the labels that each got.

#4023 Re-enable the built-in password manager
  src/browser/app/profile/zen-browser.js
Labels: Feature, size:XS, lgtm

#4027 fixed issue with mouse 4 / 5 buttons and added wrap pref to shortcuts…
  src/browser/base/zen-components/ZenWorkspaces.mjs
Labels: Bug, size:M, lgtm

#3963 Adds search to icons [DRAFT]
  src/browser/base/content/zen-popupset.inc.xhtml
  src/browser/base/content/zen-styles/zen-workspaces.css
  src/browser/base/zen-components/ZenEmojies.mjs
  src/browser/base/zen-components/ZenWorkspaces.mjs
Labels: Feature, size:L, lgtm

#3738 Add feature: Prepend '#' to custom colours for themes if '#' is not included in hex code
  src/browser/base/zen-components/ZenGradientGenerator.mjs
Labels: Feature, size:XS, lgtm

#4167 Fix #3887 and #3558
  src/browser/base/zen-components/actors/ZenThemeMarketplaceChild.sys.mjs
  src/browser/base/zen-components/actors/ZenThemeMarketplaceParent.sys.mjs
  src/browser/components/preferences/zen-settings.js
Labels: size:M, lgtm

#4158 fix: don't flash compact sidebar when opening glance
  src/browser/components/tabbrowser/content/tabs-js.patch
Labels: Bug, size:XS

#4184 Revert "fix: don't flash compact sidebar when opening glance"
  src/browser/components/tabbrowser/content/tabs-js.patch
Labels: size:XS

#4187 Make workspaces icons randomly select only non-flag emojis
  src/browser/base/zen-components/ZenWorkspaces.mjs
Labels: Enhancement, size:XS

#4198 Added collapsable header for about:support in issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Improvement, size:S, lgtm

#4282 New workspace functionality when closing last tab
  src/browser/base/content/zen-styles/zen-animations.css
  src/browser/base/content/zen-styles/zen-tabs/vertical-tabs.css
  src/browser/base/zen-components/ZenGradientGenerator.mjs
  src/browser/base/zen-components/ZenWorkspaces.mjs
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
Labels: Improvement, Enhancement, Feature, size:L

#4162 Scripts Enhacement
  build/winsign/sign.ps1
  scripts/check-rc-response.py
  scripts/prepare-flatpak-release.py
  scripts/remove-failed-jobs.sh
  scripts/update_ff.py
  scripts/update_newtab.py
Labels: Enhancement, size:XL, lgtm

#4318 Fixed grammatical error in README.md
  README.md
Labels: size:XS, lgtm

#4521 Windows build fix
  configs/common/mozconfig
Labels: Bug, size:XS
