Repository zen-browser/desktop, pull requests merged in 2025-04, with the labels that each got.

#7161 fix: tab not moving to forced workspace
  src/browser/base/zen-components/ZenWorkspaces.mjs
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
Labels: Bug, size:L, lgtm

#7288 fix: update event handling for changing tab workspace
  src/browser/base/content/zen-keysets.inc.xhtml
  src/browser/base/content/zen-sets.js
  src/browser/base/zen-components/ZenWorkspaces.mjs
Labels: Bug, size:XS, lgtm

#7292 fix: skip permitUnload when fully opening glance
  src/browser/base/zen-components/ZenGlanceManager.mjs
Labels: Bug, size:S, lgtm

#7366 Update Firefox version to 137.0 in README.md
  README.md
Labels: size:XS, lgtm

#7383 fix: change const to let
  src/browser/base/zen-components/ZenTabUnloader.mjs
Labels: size:XS, lgtm

#7397 Added transparent browser background on linux
  src/browser/app/profile/zen-browser.js
  src/browser/base/content/zen-styles/zen-theme.css
Labels: Feature, size:S, lgtm

#7400 Fix sidebar always stays left
  src/browser/base/content/zen-styles/zen-sidebar.css
Labels: Bug, size:XS, lgtm

#7396 refactor(MediaController): check pip eligibility in class
  src/browser/base/zen-components/ZenMediaController.mjs
  src/toolkit/components/pictureinpicture/PictureInPicture-sys-mjs.patch
Labels: size:XL

#7464 Allow splitting essentials and pinned tabs
  src/browser/base/zen-components/ZenViewSplitter.mjs
  surfer.json
Labels: size:M

#7569 feat(MediaController): controls for media devices
  src/browser/base/content/zen-media-controls.inc.xhtml
  src/browser/base/content/zen-sidebar-icons.inc.xhtml
  src/browser/base/content/zen-styles/zen-media-controls.css
  src/browser/base/zen-components/ZenMediaController.mjs
  src/browser/themes/shared/zen-icons/icons.css
  src/browser/themes/shared/zen-icons/jar.inc.mn
  src/browser/themes/shared/zen-icons/lin/microphone-blocked.fill.svg
  src/browser/themes/shared/zen-icons/lin/microphone.fill.svg
  src/browser/themes/shared/zen-icons/lin/video-blocked.fill.svg
  src/browser/themes/shared/zen-icons/lin/video.fill.svg
Labels: Feature, size:L, lgtm

#7573 fix(MediaController): remove sharing state when hiding
  src/browser/base/zen-components/ZenMediaController.mjs
Labels: Bug, size:XS, lgtm

#7587 fix(MediaController): more accurate sharing state
  src/browser/actors/WebRTCParent-sys-mjs.patch
  src/browser/base/zen-components/ZenMediaController.mjs
Labels: size:M, lgtm

#7588 fix(ZenMediaController): skip updaing share state when already showing
  src/browser/base/zen-components/ZenMediaController.mjs
Labels: size:XS, lgtm

#7624 fix(MediaController): update share state from same tab if not currently in sharing state
  src/browser/base/zen-components/ZenMediaController.mjs
Labels: Bug, size:XS, lgtm

#7641 Fix workspace position dragging on Linux (Fixes #7542)
  src/zen/workspaces/ZenWorkspaces.mjs
  src/zen/workspaces/zen-workspaces.css
Labels: Bug, size:M

#7672 fix: closes #7274 - Fixed mouses simulating swipes with Forward and B…
  src/zen/workspaces/ZenWorkspaces.mjs
Labels: Bug, size:S, lgtm

#7675 feat: improve tab switching with trackpad
  src/zen/workspaces/ZenWorkspaces.mjs
Labels: Feature, size:XS, lgtm

#7677 Revert "feat: improve tab switching with trackpad"
  src/zen/workspaces/ZenWorkspaces.mjs
Labels: size:XS

#7688 Smooth transition from fullscreen in compact mode
  src/zen/compact-mode/zen-compact-mode.css
Labels: size:S, lgtm

#7740 remove --cask flag from mac install instructions as it isn't necessary
  README.md
Labels: Improvement, size:XS, lgtm

#7774 Fix empty release notes sections
  .github/workflows/src/generate_release_notes.sh
Labels: Bug, size:XS, lgtm

#7771 Containerized essentials
  babel.config.json
  build/ts/transform-ts.js
  package-lock.json
  package.json
  scripts/update_ts_types.py
  src/browser/base/content/navigator-toolbox-inc-xhtml.patch
  src/browser/base/content/zen-assets.jar.inc.mn
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
  src/browser/components/tabbrowser/content/tabs-js.patch
  src/zen/@types/index.d.ts
  src/zen/@types/lib.gecko.darwin.d.ts
  src/zen/@types/lib.gecko.dom.d.ts
  src/zen/@types/lib.gecko.glean.d.ts
  src/zen/@types/lib.gecko.linux.d.ts
  src/zen/@types/lib.gecko.modules.d.ts
  src/zen/@types/lib.gecko.nsresult.d.ts
  src/zen/@types/lib.gecko.services.d.ts
  src/zen/@types/lib.gecko.tweaks.d.ts
  src/zen/@types/lib.gecko.win32.d.ts
  src/zen/@types/lib.gecko.xpcom.d.ts
  src/zen/@types/lib.gecko.xpidl.d.ts
  src/zen/@types/zen.d.ts
  src/zen/common/ZenCustomizableUI.sys.mjs
  src/zen/common/ZenStartup.mjs
  src/zen/common/ZenUIManager.mjs
  src/zen/compact-mode/ZenCompactMode.mjs
  src/zen/tabs/ZenPinnedTabManager.mjs
  src/zen/tabs/zen-tabs.css
  src/zen/tabs/zen-tabs/horizontal-tabs.css
  src/zen/tabs/zen-tabs/vertical-tabs.css
  src/zen/vendor/motion.min.mjs
  src/zen/workspaces/ZenWorkspaces.mjs
  src/zen/workspaces/ZenWorkspacesStorage.mjs
  tsconfig.json
Labels: size:XXL

#7796 Feature: Add checks for sound before auto toggling PiP
  src/toolkit/actors/PictureInPictureChild-sys-mjs.patch
  src/toolkit/components/pictureinpicture/PictureInPicture-sys-mjs.patch
Labels: Feature, size:S

#7761 Fix tab switching crash when creating new tabs (Issue #7716)
  src/zen/common/ZenUIManager.mjs
  src/zen/workspaces/ZenWorkspaces.mjs
Labels: Bug, size:L, lgtm

#7831 add horizontal bar simular to vertical in split view
  src/zen/common/styles/zen-browser-ui.css
Labels: Feature, size:S

#7846 Homepage button on Zen Mods settings page.
  src/browser/components/preferences/zen-settings.js
  src/browser/themes/shared/preferences/zen-preferences.css
Labels: Improvement, size:M, lgtm

#7857 Keep Firefox name consistent + fix typos
  README.md
  build/winsign/sign.ps1
  docs/issue-metrics/2024_2024-11-01..2024-11-30.md
  docs/issue-metrics/2024_2024-12-01..2024-12-31.md
  docs/issue-metrics/2025_2025-01-01..2025-01-31.md
  docs/issue-metrics/2025_2025-02-01..2025-02-28.md
  docs/issue-metrics/2025_2025-03-01..2025-03-31.md
  docs/workspaces.md
  src/browser/app/profile/zen-browser.js
  src/firefox-patches/README.md
  src/zen/common/styles/zen-browser-ui.css
  src/zen/common/styles/zen-popup.css
  src/zen/common/zenThemeModifier.js
  src/zen/kbs/ZenKeyboardShortcuts.mjs
Labels: size:M

#7861 fix: Fixed workspace context menu not working, b=(no-bug), c=workspaces
  src/zen/workspaces/ZenWorkspaces.mjs
Labels: size:XS

#7862 fix: Fixed media controller mute not updating tab mute state
  src/zen/media/ZenMediaController.mjs
Labels: Bug, size:S, lgtm

#7690 Download animation
  src/browser/app/profile/zen-browser.js
  src/browser/base/content/zen-assets.inc.xhtml
  src/browser/base/content/zen-assets.jar.inc.mn
  src/zen/downloads/ZenDownloadAnimation.mjs
  src/zen/downloads/zen-download-arc-animation.css
  src/zen/downloads/zen-download-box-animation.css
  src/zen/images/downloads/archive.svg
  src/zen/images/downloads/download.svg
Labels: Feature, size:XL, lgtm

#7901 Better privacy and less connections on startup
  configs/common/mozconfig
  src/browser/app/profile/zen-browser.js
  src/zen/common/ZenUIManager.mjs
  src/zen/tabs/ZenPinnedTabManager.mjs
  src/zen/welcome/ZenWelcome.mjs
Labels: Improvement, size:M, component: privacy

#7903 feat: Changed favicon URLs to private-cdn.zen-browser.app, b=(no-bug)…
  src/zen/compact-mode/zen-compact-mode.css
  src/zen/tabs/zen-tabs/vertical-tabs.css
  src/zen/welcome/ZenWelcome.mjs
  src/zen/workspaces/ZenWorkspaces.mjs
Labels: size:M

#7921 fix: cache initial pinned tabs favicon
  src/zen/tabs/ZenPinnedTabManager.mjs
  src/zen/welcome/ZenWelcome.mjs
Labels: size:M, lgtm
