Repository zen-browser/desktop, pull requests merged in 2025-09, with the labels that each got.

#10194 New Crowdin updates
  locales/ga-IE/browser/browser/zen-folders.ftl
  locales/pt-BR/browser/browser/zen-folders.ftl
Labels: size:XS

#10201 fix: hide manage themes option in customize toolbar
  src/zen/common/styles/zen-single-components.css
Labels: Bug, size:XS, lgtm

#10213 New Crowdin updates
  locales/cs/browser/browser/zen-folders.ftl
  locales/zh-CN/browser/browser/preferences/zen-preferences.ftl
  locales/zh-CN/browser/browser/zen-folders.ftl
  locales/zh-CN/browser/browser/zen-general.ftl
  locales/zh-CN/browser/browser/zen-vertical-tabs.ftl
  locales/zh-CN/browser/browser/zen-workspaces.ftl
Labels: size:M

#10233 feat: add tada & at icons for ZenEmojiPicker
  src/browser/themes/shared/zen-icons/common/selectable/at.svg
  src/browser/themes/shared/zen-icons/common/selectable/tada.svg
  src/browser/themes/shared/zen-icons/jar.inc.mn
  src/zen/common/emojis/ZenEmojiPicker.mjs
Labels: Feature, size:XS, lgtm

#10258 Remove unnecessary filesystem permissions
  .well-known/funding-manifest-urls
  build/flatpak/app.zen_browser.zen.yml.template
Labels: size:XS

#10343 New Crowdin updates
  locales/cs/browser/browser/preferences/zen-preferences.ftl
  locales/fr/browser/browser/preferences/zen-preferences.ftl
  locales/fr/browser/browser/zen-folders.ftl
  locales/fr/browser/browser/zen-general.ftl
  locales/fr/browser/browser/zen-welcome.ftl
  locales/fr/browser/browser/zen-workspaces.ftl
  locales/ga-IE/browser/browser/preferences/zen-preferences.ftl
  locales/id/browser/browser/preferences/zen-preferences.ftl
  locales/id/browser/browser/zen-folders.ftl
  locales/zh-TW/browser/browser/preferences/zen-preferences.ftl
  locales/zh-TW/browser/browser/zen-folders.ftl
  locales/zh-TW/browser/browser/zen-general.ftl
  locales/zh-TW/browser/browser/zen-split-view.ftl
  locales/zh-TW/browser/browser/zen-vertical-tabs.ftl
  locales/zh-TW/browser/browser/zen-welcome.ftl
  locales/zh-TW/browser/browser/zen-workspaces.ftl
Labels: size:L

#10376 fix: change prettyName element from strong to span
  src/zen/urlbar/ZenUBActionsProvider.sys.mjs
Labels: size:XS, lgtm

#10392 fix: Split View is not displayed when performing animateSelect
  src/zen/folders/ZenFolders.mjs
Labels: Bug, size:S, lgtm

#10393 fix: repeating right sidebar gradient in compact mode
  src/zen/compact-mode/zen-compact-mode.css
Labels: Bug, size:XS, lgtm

#10385 New Crowdin updates
  locales/ga-IE/browser/browser/preferences/zen-preferences.ftl
  locales/ga-IE/browser/browser/zen-workspaces.ftl
  locales/pt-PT/browser/browser/preferences/zen-preferences.ftl
  locales/pt-PT/browser/browser/zen-workspaces.ftl
  locales/zh-CN/browser/browser/preferences/zen-preferences.ftl
Labels: size:S

#10121 Issue 6968: Allow essential tabs to bypass workspace exclusion as owners
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
Labels: Feature, size:L

#10417 feat: Added more urlbar commands, b=no-bug, c=workspaces
  src/zen/urlbar/ZenUBGlobalActions.sys.mjs
Labels: Feature, size:M, lgtm

#10421 New Crowdin updates
  locales/ar/browser/browser/preferences/zen-preferences.ftl
  locales/ca/browser/browser/preferences/zen-preferences.ftl
  locales/cs/browser/browser/preferences/zen-preferences.ftl
  locales/cy/browser/browser/preferences/zen-preferences.ftl
  locales/da/browser/browser/preferences/zen-preferences.ftl
  locales/de/browser/browser/preferences/zen-preferences.ftl
  locales/el/browser/browser/preferences/zen-preferences.ftl
  locales/en-GB/browser/browser/preferences/zen-preferences.ftl
  locales/es-ES/browser/browser/preferences/zen-preferences.ftl
  locales/et/browser/browser/preferences/zen-preferences.ftl
  locales/fa/browser/browser/preferences/zen-preferences.ftl
  locales/fi/browser/browser/preferences/zen-preferences.ftl
  locales/fr/browser/browser/preferences/zen-preferences.ftl
  locales/ga-IE/browser/browser/preferences/zen-preferences.ftl
  locales/he/browser/browser/preferences/zen-preferences.ftl
  locales/hu/browser/browser/preferences/zen-preferences.ftl
  locales/id/browser/browser/preferences/zen-preferences.ftl
  locales/is/browser/browser/preferences/zen-preferences.ftl
  locales/it/browser/browser/preferences/zen-preferences.ftl
  locales/ja/browser/browser/preferences/zen-preferences.ftl
  locales/ko/browser/browser/preferences/zen-preferences.ftl
  locales/ko/browser/browser/zen-workspaces.ftl
  locales/lt/browser/browser/preferences/zen-preferences.ftl
  locales/nl/browser/browser/preferences/zen-preferences.ftl
  locales/nn-NO/browser/browser/preferences/zen-preferences.ftl
  locales/pl/browser/browser/preferences/zen-preferences.ftl
  locales/pt-BR/browser/browser/preferences/zen-preferences.ftl
  locales/pt-PT/browser/browser/preferences/zen-preferences.ftl
  locales/ru/browser/browser/preferences/zen-preferences.ftl
  locales/sv-SE/browser/browser/preferences/zen-preferences.ftl
  locales/th/browser/browser/preferences/zen-preferences.ftl
  locales/tr/browser/browser/preferences/zen-preferences.ftl
  locales/uk/browser/browser/preferences/zen-preferences.ftl
  locales/vi/browser/browser/preferences/zen-preferences.ftl
  locales/zh-CN/browser/browser/preferences/zen-preferences.ftl
  locales/zh-TW/browser/browser/preferences/zen-preferences.ftl
Labels: Improvement, size:M

#10431 fix: remove extra spaces between words when renaming a tab/folder
  src/zen/common/ZenUIManager.mjs
Labels: Bug, size:XS, lgtm

#10440 fix: animateUnload for folder
  src/zen/folders/ZenFolder.mjs
  src/zen/folders/ZenFolders.mjs
  src/zen/split-view/zen-decks.css
  src/zen/tabs/ZenPinnedTabManager.mjs
Labels: size:L, lgtm

#10448 Revert "fix: animateUnload for folder"
  src/zen/folders/ZenFolder.mjs
  src/zen/folders/ZenFolders.mjs
  src/zen/split-view/zen-decks.css
  src/zen/tabs/ZenPinnedTabManager.mjs
Labels: size:L

#10453 New Crowdin updates
  locales/de/browser/browser/preferences/zen-preferences.ftl
  locales/de/browser/browser/zen-workspaces.ftl
  locales/id/browser/browser/preferences/zen-preferences.ftl
  locales/pt-BR/browser/browser/preferences/zen-preferences.ftl
  locales/pt-BR/browser/browser/zen-workspaces.ftl
  locales/pt-PT/browser/browser/preferences/zen-preferences.ftl
  locales/uk/browser/browser/preferences/zen-preferences.ftl
  locales/uk/browser/browser/zen-workspaces.ftl
Labels: size:M

#10572 Revert "chore: update flatpak runtime to 25.08"
  build/flatpak/app.zen_browser.zen.yml.template
Labels: size:XS

#10564 feat: Add learning for omnibox commands
  locales/en-US/browser/browser/zen-general.ftl
  package.json
  src/browser/components/sessionstore/TabState-sys-mjs.patch
  src/browser/components/urlbar/UrlbarController-sys-mjs.patch
  src/browser/components/urlbar/UrlbarInput-sys-mjs.patch
  src/browser/components/urlbar/UrlbarMuxerStandard-sys-mjs.patch
  src/browser/components/urlbar/UrlbarPrefs-sys-mjs.patch
  src/browser/components/urlbar/UrlbarUtils-sys-mjs.patch
  src/browser/components/urlbar/UrlbarView-sys-mjs.patch
  src/zen/common/ZenCommonUtils.mjs
  src/zen/common/ZenStartup.mjs
  src/zen/common/ZenUIManager.mjs
  src/zen/common/styles/zen-animations.css
  src/zen/common/styles/zen-browser-ui.css
  src/zen/common/styles/zen-omnibox.css
  src/zen/common/zenThemeModifier.js
  src/zen/compact-mode/ZenCompactMode.mjs
  src/zen/compact-mode/zen-compact-mode.css
  src/zen/split-view/ZenViewSplitter.mjs
  src/zen/urlbar/ZenUBActionsProvider.sys.mjs
  src/zen/urlbar/ZenUBGlobalActions.sys.mjs
  src/zen/urlbar/ZenUBResultsLearner.sys.mjs
  src/zen/urlbar/moz.build
  surfer.json
Labels: Feature, size:XL

#10588 feat: Improved startup performance and flashes
  src/zen/ZenComponents.manifest
  src/zen/common/ZenStartup.mjs
  src/zen/moz.build
  src/zen/tabs/zen-tabs/vertical-tabs.css
  src/zen/workspaces/ZenWorkspaces.mjs
Labels: Feature, size:L

#10604 Revert "feat: Improved startup performance and flashes"
  src/zen/ZenComponents.manifest
  src/zen/common/ZenStartup.mjs
  src/zen/moz.build
  src/zen/tabs/zen-tabs/vertical-tabs.css
  src/zen/workspaces/ZenWorkspaces.mjs
Labels: size:L

#10606 fix: zen.source ignore VCS data
  .github/workflows/build.yml
Labels: Bug, size:XS, lgtm

#10607 fix: zen.source exclude-vcs breaks submodules checksums
  .github/workflows/build.yml
Labels: Bug, size:XS
