Repository zen-browser/desktop, pull requests merged in 2025-05, with the labels that each got.

#8253 Add patch fix #7701
  src/browser/app/profile/disablemozilla.inc
Labels: Bug, size:XS, lgtm

#8256 Add fix for #7810
  src/browser/components/preferences/zen-settings.js
Labels: Bug, size:S

#8261 Fix for #7910
  src/zen/glance/ZenGlanceManager.mjs
  src/zen/glance/zen-glance.css
Labels: Bug, size:S, lgtm

#8243 New share API and implementation
  package-lock.json
  package.json
  src/browser/themes/shared/zen-icons/icons.css
  src/zen/common/ZenCommonUtils.mjs
  src/zen/common/ZenUIManager.mjs
  src/zen/common/styles/zen-popup.css
  src/zen/moz.build
  src/zen/toolkit/common/ZenCommonUtils.cpp
  src/zen/toolkit/common/ZenCommonUtils.h
  src/zen/toolkit/common/ZenShareInternal.h
  src/zen/toolkit/common/cocoa/ZenShareInternal.mm
  src/zen/toolkit/common/cocoa/moz.build
  src/zen/toolkit/common/components.conf
  src/zen/toolkit/common/moz.build
  src/zen/toolkit/common/nsIZenCommonUtils.idl
  src/zen/toolkit/common/windows/ZenShareInternal.cpp
  src/zen/toolkit/common/windows/moz.build
  src/zen/toolkit/moz.build
Labels: Feature, size:XL

#8265 Added workspace color bg to search mode indicators
  src/zen/common/styles/zen-urlbar.css
Labels: Improvement, size:XS, lgtm

#8266 Haptic feedback support
  src/browser/app/profile/features.inc
  src/modules/libpref/init/zen-static-prefs.inc
  src/zen/common/styles/zen-panel-ui.css
  src/zen/tabs/ZenPinnedTabManager.mjs
  src/zen/toolkit/common/ZenCommonUtils.cpp
  src/zen/toolkit/common/ZenCommonUtils.h
  src/zen/toolkit/common/cocoa/ZenHapticFeedback.mm
  src/zen/toolkit/common/cocoa/ZenShareInternal.mm
  src/zen/toolkit/common/cocoa/moz.build
  src/zen/toolkit/common/nsIZenCommonUtils.idl
  src/zen/workspaces/ZenGradientGenerator.mjs
  src/zen/workspaces/zen-gradient-generator.css
Labels: Feature, size:L

#8279 Potential fix for code scanning alert no. 18: Overly permissive regular expression range
  src/zen/mods/ZenThemesCommon.mjs
Labels: size:XS

#8280 Potential fix for code scanning alert no. 19: Overly permissive regular expression range
  src/zen/mods/ZenThemesImporter.mjs
Labels: size:XS

#8281 Potential fix for code scanning alert no. 17: Overly permissive regular expression range
  src/browser/components/preferences/zen-settings.js
Labels: size:XS

#8283 Potential fix for code scanning alert no. 15: Workflow does not contain permissions
  .github/workflows/windows-release-build.yml
Labels: size:XS

#8284 Potential fix for code scanning alert no. 14: Workflow does not contain permissions
  .github/workflows/windows-profile-build.yml
Labels: size:XS

#8285 Potential fix for code scanning alert no. 13: Workflow does not contain permissions
  .github/workflows/twilight-release-schedule.yml
Labels: size:XS

#8290 Potential fix for code scanning alert no. 12: Workflow does not contain permissions
  .github/workflows/pr-test.yml
Labels: size:XS

#8289 Potential fix for code scanning alert no. 1: Workflow does not contain permissions
  .github/workflows/check-candidate-release.yml
Labels: size:XS

#8287 Potential fix for code scanning alert no. 5: Workflow does not contain permissions
  .github/workflows/issue-metrics.yml
Labels: size:XS

#8291 Potential fix for code scanning alert no. 11: Workflow does not contain permissions
  .github/workflows/build.yml
Labels: size:XS

#8292 Potential fix for code scanning alert no. 8: Workflow does not contain permissions
  .github/workflows/macos-release-build.yml
Labels: size:XS

#8294 Potential fix for code scanning alert no. 6: Workflow does not contain permissions
  .github/workflows/build.yml
Labels: size:XS

#8296 Revert "Potential fix for code scanning alert no. 6: Workflow does not contain permissions"
  .github/workflows/build.yml
Labels: size:XS

#8298 Revert "Potential fix for code scanning alert no. 11: Workflow does not contain permissions"
  .github/workflows/build.yml
Labels: size:XS

#8299 Revert "Potential fix for code scanning alert no. 16: Workflow does not contain permissions"
  .github/workflows/build.yml
Labels: size:XS

#8300 Revert "Potential fix for code scanning alert no. 9: Workflow does not contain permissions"
  .github/workflows/macos-universal-release-build.yml
Labels: size:XS

#8340 Fix #7609 by changing to orange when white.
  src/browser/themes/shared/preferences/zen-preferences.css
Labels: Bug, size:XS, lgtm

#8384 bugfix(mods): add file download retry and try catchs to fallback on f…
  src/zen/mods/ZenThemesCommon.mjs
  src/zen/mods/ZenThemesImporter.mjs
  src/zen/mods/actors/ZenThemeMarketplaceChild.sys.mjs
  src/zen/mods/actors/ZenThemeMarketplaceParent.sys.mjs
Labels: Bug, size:L, lgtm, component: mods-themes

#8578 fix: Fixed restoring previous sesions from empty tabs, b=(no-bug), c=…
  src/browser/components/sessionstore/SessionStore-sys-mjs.patch
Labels: size:S

#8661 Add a unique id to the checkbox for auto-updating Zen Mods on startup.
  src/browser/components/preferences/zenMarketplace.inc.xhtml
Labels: Improvement, size:XS, lgtm

#8671 chore: Added new readme, b=(no-bug), c=no-component
  README.md
Labels: size:L

#8739 Update release notes script
  .github/workflows/src/generate_release_notes.sh
Labels: size:L, lgtm
