Repository zen-browser/desktop, pull requests merged in 2025-02, with the labels that each got.

#5224 Improve corner radius on windows for a more native and consistent look (very minor change, not tested)
  src/browser/app/profile/zen-browser.js
Labels: Improvement, size:XS

#5273 Started working on new workspaec layout
  src/browser/base/content/ZenStartup.mjs
  src/browser/base/content/ZenUIManager.mjs
  src/browser/base/content/navigator-toolbox-inc-xhtml.patch
  src/browser/base/content/zen-styles/zen-browser-ui.css
  src/browser/base/content/zen-styles/zen-tabs/horizontal-tabs.css
  src/browser/base/content/zen-styles/zen-tabs/vertical-tabs.css
  src/browser/base/content/zen-styles/zen-theme.css
  src/browser/base/content/zen-styles/zen-urlbar.css
  src/browser/base/content/zen-styles/zen-workspaces.css
  src/browser/base/zen-components/ZenGradientGenerator.mjs
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
  src/browser/base/zen-components/ZenWorkspaces.mjs
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
  src/browser/components/tabbrowser/content/tabs-js.patch
  src/browser/themes/shared/tabbrowser/tabs-css.patch
Labels: size:XL

#5342 Fix text rendering issues by decreasing gfx.canvas.accelerated.cache-size back to Firefox default
  src/browser/app/profile/zen-browser.js
Labels: Bug, size:XS

#4734 Add Bat to ZenEmojies
  src/browser/base/zen-components/ZenEmojies.mjs
Labels: size:XS, lgtm

#5235 Add split view support for tab dragging and rearranging
  src/browser/base/content/zen-styles/zen-decks.css
  src/browser/base/zen-components/ZenViewSplitter.mjs
Labels: Feature, size:L

#5474 Fix: Update pinned tab title in storage on rename
  src/browser/base/content/ZenUIManager.mjs
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
  src/browser/base/zen-components/ZenPinnedTabsStorage.mjs
  src/browser/base/zen-components/ZenWorkspaces.mjs
Labels: Bug, size:L, lgtm

#5457 fixed issues and added button functionality
  src/browser/base/content/zen-popupset.inc.xhtml
  src/browser/base/content/zen-styles/zen-gradient-generator.css
  src/browser/base/zen-components/ZenGradientGenerator.mjs
Labels: size:L, lgtm

#5485 fixed padding and undifined algo error
  src/browser/base/zen-components/ZenGradientGenerator.mjs
Labels: size:M

#5508 fixed issue with primary colors hopefully
  src/browser/base/zen-components/ZenGradientGenerator.mjs
Labels: size:S

#4792 Added a preference to toggle the sidebar opening on hover in compact mode
  src/browser/app/profile/zen-browser.js
  src/browser/base/zen-components/ZenCompactMode.mjs
Labels: size:S, lgtm

#5537 Better aligment for add custom color button
  src/browser/base/content/zen-styles/zen-gradient-generator.css
Labels: Improvement, size:XS, lgtm

#5543 Revert "Add Bat to ZenEmojies"
  src/browser/base/zen-components/ZenEmojies.mjs
Labels: size:XS

#5544 Finish the "Show sidebar on hover" PR
  src/browser/base/content/zen-styles/zen-compact-mode.css
Labels: Bug, size:XS

#5642 Fixed add color icon alignment issue
  src/browser/base/content/zen-styles/zen-gradient-generator.css
Labels: Bug, size:XS, lgtm

#5680 Fixed workspace indicator margin for windows
  src/browser/base/content/zen-styles/zen-workspaces.css
Labels: size:XS

#5730 Native English proofread on README
  README.md
Labels: Improvement, size:S, lgtm

#5898 README: specify license version
  README.md
Labels: size:XS, lgtm

#5914 Allow having full url without https in sidebar
  src/browser/app/profile/zen-browser.js
  src/browser/base/content/ZenUIManager.mjs
Labels: Feature, size:XS, lgtm
