Repository zen-browser/desktop, pull requests merged in 2025-03, with the labels that each got.

#5976 Fix: bookmark items not opening
  src/browser/components/places/PlacesUIUtils-sys-mjs.patch
Labels: Bug, size:S, lgtm

#5634 Implement a more complete JXL features
  src/Cargo-lock.patch
  src/Cargo-toml.patch
  src/browser/components/BrowserContentHandler-sys-mjs.patch
  src/browser/installer/windows/msix/AppxManifest-xml-in.patch
  src/browser/installer/windows/nsis/shared-nsh.patch
  src/browser/installer/windows/nsis/uninstaller-nsi.patch
  src/image/DecoderFactory-cpp.patch
  src/image/decoders/nsJXLDecoder-cpp.patch
  src/image/decoders/nsJXLDecoder-h.patch
  src/third_party/rust/mime_guess/src/mime_types-rs.patch
  src/toolkit/components/downloads/DownloadList-sys-mjs.patch
  src/toolkit/components/extensions/parent/ext-downloads-js.patch
  src/toolkit/content/filepicker-properties.patch
  src/toolkit/locales/en-US/chrome/mozapps/downloads/unknownContentType-properties.patch
  src/widget/gtk/nsAppShell-cpp.patch
Labels: Feature, size:XL

#5467 keep the "pinned" attribute of the side web panel and the button in sync
  src/browser/base/content/zen-sidebar-panel.inc.xhtml
  src/browser/base/zen-components/ZenSidebarManager.mjs
Labels: size:S

#5988 Hide empty tab from add-ons
  src/browser/components/extensions/parent/ext-browser-js.patch
Labels: size:S

#5999 Report JXL frame counts properly
  src/image/decoders/nsJXLDecoder-cpp.patch
Labels: size:S

#6021 Feature: add martial arts uniform emoji
  src/browser/base/zen-components/ZenEmojies.mjs
Labels: Feature, size:XS, lgtm

#6072 Fix: External link not opening in default container
  src/browser/base/zen-components/ZenWorkspaces.mjs
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
Labels: Bug, size:XS, lgtm

#6082 Feat: add drag event support for compact mode
  src/browser/base/zen-components/ZenCompactMode.mjs
Labels: Feature, size:S, lgtm

#6086 fix appimage not being able to set itself as default web browser
  AppDir/AppRun
Labels: Bug, size:XS, lgtm

#6104 Update README.md: fix small typo on version format
  README.md
Labels: size:XS, lgtm

#6116 Fix compact mode top toolbar hiding prematurely
  src/browser/base/zen-components/ZenCompactMode.mjs
Labels: Bug, size:XS, lgtm

#6130 fix crash on sleep by switching appimage runtime
  .github/workflows/build.yml
Labels: Bug, size:S, lgtm

#6204 Enhance ZenViewSplitter to support dynamic side detection for split v…
  src/browser/base/content/ZenUIManager.mjs
  src/browser/base/content/zen-styles/zen-decks.css
  src/browser/base/zen-components/ZenViewSplitter.mjs
  src/browser/components/tabbrowser/content/tabs-js.patch
Labels: Enhancement, size:L

#6156 remove unnecesary declation of several variables
  AppDir/AppRun
Labels: Improvement, size:S, lgtm

#6244 Disable AI chat stuff by default
  src/browser/app/profile/zen-browser.js
Labels: Improvement, size:XS, lgtm

#6256 Fix wrong variable being used for splitting tab view
  src/browser/base/zen-components/ZenViewSplitter.mjs
Labels: Bug, twilight, size:XS, lgtm

#6324 Fix toolbar not hiding after minimizing
  src/browser/base/zen-components/ZenCompactMode.mjs
Labels: Bug, size:S, lgtm

#6390 Generate release notes for Github releases
  .github/workflows/build.yml
  .github/workflows/src/generate_release_notes.sh
Labels: Improvement, size:L

#6321 Feat: basic media control
  src/browser/base/zen-components/ZenMediaController.mjs
  src/dom/html/HTMLMediaElement-cpp.patch
  src/toolkit/actors/AudioPlaybackParent-sys-mjs.patch
Labels: Feature, size:M, lgtm

#6417 Media control
  src/browser/base/content/ZenUIManager.mjs
  src/browser/base/content/zen-assets.inc.xhtml
  src/browser/base/content/zen-assets.jar.inc.mn
  src/browser/base/content/zen-media-player.inc.xhtml
  src/browser/base/content/zen-sidebar-icons.inc.xhtml
  src/browser/base/content/zen-styles/zen-media-controls.css
  src/browser/base/zen-components/ZenMediaController.mjs
  src/browser/themes/shared/zen-icons/icons.css
  src/browser/themes/shared/zen-icons/jar.inc.mn
  src/browser/themes/shared/zen-icons/lin/media-next.svg
  src/browser/themes/shared/zen-icons/lin/media-pause.svg
  src/browser/themes/shared/zen-icons/lin/media-play.svg
  src/browser/themes/shared/zen-icons/lin/media-previous.svg
  src/dom/chrome-webidl/MediaController-webidl.patch
  src/dom/html/HTMLMediaElement-cpp.patch
  src/dom/media/mediacontrol/MediaController-cpp.patch
  src/dom/media/mediacontrol/MediaController-h.patch
  src/toolkit/actors/AudioPlaybackParent-sys-mjs.patch
Labels: size:XL

#6449 add negative margin to focus button when hidden
  src/browser/base/content/zen-styles/zen-media-controls.css
  src/browser/base/zen-components/ZenMediaController.mjs
Labels: Enhancement, size:XS, lgtm

#6465 make installation guide on other linux distros less confusing
  README.md
Labels: Improvement, size:S, lgtm

#6472 Fixes for media control
  src/browser/base/zen-components/ZenMediaController.mjs
  src/toolkit/actors/AudioPlaybackParent-sys-mjs.patch
Labels: Bug, size:M, lgtm

#6486 Fix bash install command in documentation on how to install for Linux using tarball
  README.md
Labels: size:XS, lgtm

#6499 New features for media control
  src/browser/base/content/zen-media-player.inc.xhtml
  src/browser/base/content/zen-styles/zen-media-controls.css
  src/browser/base/zen-components/ZenMediaController.mjs
  src/browser/themes/shared/zen-icons/icons.css
  src/toolkit/components/pictureinpicture/PictureInPicture-sys-mjs.patch
Labels: Feature, size:L, lgtm

#6535 enhance media focus handling to support sidebar opening
  src/browser/base/zen-components/ZenMediaController.mjs
  src/browser/base/zen-components/ZenSidebarManager.mjs
Labels: Enhancement, size:XS, lgtm

#6559 Fix stable build release notes generation
  .github/workflows/build.yml
Labels: size:XS, lgtm

#6588 fix: private window reordering and split tabs
  src/browser/base/zen-components/ZenPinnedTabManager.mjs
Labels: Bug, size:XS, lgtm

#6618 styles: use tabular-nums on media controls
  src/browser/base/content/zen-styles/zen-media-controls.css
Labels: Enhancement, size:XS, lgtm

#6625 fix(MediaController): restore scrollbar when updating ui
  src/browser/base/zen-components/ZenMediaController.mjs
Labels: Bug, size:S

#6563 Update flatpak manifest file
  flatpak/app.zen_browser.zen.yml.template
Labels: size:XS

#6649 add config to disable media controls
  src/browser/app/profile/zen-browser.js
  src/browser/base/zen-components/ZenMediaController.mjs
Labels: Feature, size:XS, lgtm

#6629 feat: add minimize button to pip window
  src/toolkit/components/pictureinpicture/content/player-js.patch
  src/toolkit/components/pictureinpicture/content/player-xhtml.patch
  src/toolkit/themes/shared/pictureinpicture/player-css.patch
Labels: Feature, size:M

#6710 fix(MediaController): recheck overflow on metadata change
  src/browser/base/zen-components/ZenMediaController.mjs
Labels: Bug, size:XS, lgtm

#6706 fix: import string to pip window
  src/toolkit/components/pictureinpicture/content/player-xhtml.patch
Labels: size:S

#5842 Fix: fixed overflowing glance buttons when sidebar is opened
  src/browser/base/content/zen-glance.inc.xhtml
  src/browser/base/content/zen-styles/zen-glance.css
  src/browser/base/zen-components/ZenGlanceManager.mjs
Labels: Bug, size:L, lgtm

#6738 Update README.md to set user expectations
  README.md
Labels: size:XS

#6745 Revert "Fix: fixed overflowing glance buttons when sidebar is opened"
  src/browser/base/content/zen-glance.inc.xhtml
  src/browser/base/content/zen-styles/zen-glance.css
  src/browser/base/zen-components/ZenGlanceManager.mjs
Labels: size:L

#6774 fix: media controls config typo
  src/browser/app/profile/zen-browser.js
Labels: Bug, size:XS, lgtm

#6775 MediaController: update position more frequently
  src/dom/html/HTMLMediaElement-cpp.patch
Labels: Bug, size:S, lgtm

#6777 Removed weird movement when hovering media player
  src/browser/base/content/zen-styles/zen-media-controls.css
Labels: size:XS, lgtm

#6788 Fix: small typo
  src/browser/base/zen-components/actors/ZenThemeMarketplaceChild.sys.mjs
Labels: size:XS

#6740 Update update_newtab.py
  scripts/update_newtab.py
Labels: Enhancement, size:M

#6793 Added support for split views persisting between sessions
  src/browser/base/content/zen-styles/zen-folders.css
  src/browser/base/content/zen-styles/zen-popup.css
  src/browser/base/zen-components/ZenViewSplitter.mjs
  src/browser/base/zen-components/ZenWorkspaces.mjs
  src/browser/components/sessionstore/SessionStore-sys-mjs.patch
  src/browser/components/sessionstore/TabGroupState-sys-mjs.patch
  src/browser/components/sessionstore/TabState-sys-mjs.patch
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
  src/browser/components/tabbrowser/content/tabs-js.patch
  src/toolkit/content/widgets/findbar-js.patch
Labels: size:L

#6814 fix(MediaController): pass in playbackRate when switching controller
  src/browser/base/zen-components/ZenMediaController.mjs
Labels: size:XS, lgtm

#6818 refactor(MediaController): remove redundant code
  src/browser/base/zen-components/ZenMediaController.mjs
Labels: Improvement, size:S, lgtm

#6909 Fix: Wrong dialog width in compact view
  src/browser/base/content/zen-styles/zen-panels/dialog.css
Labels: Bug, size:XS

#6956 Enhance bug report template and add issue labeling workflow
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/advanced-issue-labeler.yml
  .github/workflows/clear-cache.yml
  .github/workflows/issue-labeler.yml
Labels: size:L, lgtm

#7036 Build cache improvement
  scripts/download-language-packs.sh
  scripts/update_ff.py
Labels: size:XS

#7064 fix: prevent attaching ID to empty tab in extension TabTracker
  src/browser/components/extensions/parent/ext-browser-js.patch
Labels: Bug, size:S

#7126 fix: handle undefined ZenWorkspaces in tab selection
  src/toolkit/content/widgets/tabbox-js.patch
Labels: size:XS, lgtm
