Repository zen-browser/desktop, pull requests merged in 2025-08, with the labels that each got.

#9722 fix: legacy gradients setting being ignored after opening a private window
  src/zen/workspaces/ZenGradientGenerator.mjs
Labels: Bug, size:XS, lgtm

#9700 New Crowdin updates
  locales/pl/browser/browser/preferences/zen-preferences.ftl
  locales/pl/browser/browser/zen-folders.ftl
  locales/pl/browser/browser/zen-vertical-tabs.ftl
  locales/pt-BR/browser/browser/preferences/zen-preferences.ftl
  locales/uk/browser/browser/preferences/zen-preferences.ftl
  locales/uk/browser/browser/zen-vertical-tabs.ftl
Labels: size:M

#9736 New Crowdin updates
  locales/de/browser/browser/preferences/zen-preferences.ftl
  locales/de/browser/browser/zen-general.ftl
  locales/de/browser/browser/zen-split-view.ftl
  locales/de/browser/browser/zen-vertical-tabs.ftl
  locales/de/browser/browser/zen-welcome.ftl
  locales/de/browser/browser/zen-workspaces.ftl
  locales/he/browser/browser/zen-folders.ftl
  locales/id/browser/browser/zen-folders.ftl
Labels: Improvement, size:L

#9774 fix: Correct drag-and-drop targeting for split-view group labels
  src/browser/components/tabbrowser/content/tabs-js.patch
  src/zen/folders/zen-folders.css
Labels: size:M, lgtm

#9797 New Crowdin updates
  locales/cs/browser/browser/zen-folders.ftl
  locales/ga-IE/browser/browser/zen-folders.ftl
  locales/ga-IE/browser/browser/zen-general.ftl
  locales/ga-IE/browser/browser/zen-workspaces.ftl
  locales/hu/browser/browser/zen-general.ftl
  locales/hu/browser/browser/zen-workspaces.ftl
  locales/ko/browser/browser/preferences/zen-preferences.ftl
  locales/ko/browser/browser/zen-folders.ftl
  locales/ko/browser/browser/zen-general.ftl
  locales/ko/browser/browser/zen-vertical-tabs.ftl
  locales/ko/browser/browser/zen-welcome.ftl
  locales/ko/browser/browser/zen-workspaces.ftl
Labels: size:M

#9841 fix: Split view group have an extra group after session restore
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
Labels: Bug, size:L, lgtm

#9899 fix: During session restore `insertBefore` creates an extra group for
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
Labels: size:M, lgtm

#9906 fix: Cannot delete a folder or rename it if clicking on the text
  src/zen/folders/ZenFolders.mjs
Labels: Bug, size:S

#9908 feat: Improved indentation when dragging tabs and folders
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
  src/browser/components/tabbrowser/content/tabgroup-js.patch
  src/browser/components/tabbrowser/content/tabs-js.patch
  src/zen/folders/ZenFolder.mjs
  src/zen/folders/ZenFolders.mjs
Labels: Feature, size:L

#9941 feat: Multiselected tabs support
  package.json
  src/browser/components/tabbrowser/content/tab-js.patch
  src/zen/folders/ZenFolder.mjs
  src/zen/folders/ZenFolders.mjs
  src/zen/folders/zen-folders.css
  src/zen/tabs/ZenPinnedTabManager.mjs
  src/zen/tests/folders/browser.toml
  src/zen/tests/folders/browser_folder_level_checks.js
  src/zen/tests/folders/browser_folder_multiselected.js
  src/zen/tests/folders/browser_folder_visible_tabs.js
Labels: Feature, size:XL, lgtm

#9983 fix: calculate margin-top after expand animation
  src/zen/folders/ZenFolders.mjs
Labels: size:M, lgtm

#9985 fix: some minor fixes
  src/zen/folders/ZenFolders.mjs
Labels: size:S, lgtm

#10038 fix: Some fixes for folders
  src/browser/components/tabbrowser/content/tabbrowser-js.patch
  src/zen/folders/ZenFolders.mjs
Labels: size:M, lgtm

#10055 New Crowdin updates
  locales/ar/browser/browser/zen-vertical-tabs.ftl
  locales/ca/browser/browser/zen-vertical-tabs.ftl
  locales/cs/browser/browser/zen-vertical-tabs.ftl
  locales/cy/browser/browser/zen-vertical-tabs.ftl
  locales/da/browser/browser/zen-vertical-tabs.ftl
  locales/de/browser/browser/zen-folders.ftl
  locales/de/browser/browser/zen-vertical-tabs.ftl
  locales/el/browser/browser/zen-vertical-tabs.ftl
  locales/en-GB/browser/browser/zen-vertical-tabs.ftl
  locales/es-ES/browser/browser/zen-vertical-tabs.ftl
  locales/et/browser/browser/zen-vertical-tabs.ftl
  locales/fa/browser/browser/zen-vertical-tabs.ftl
  locales/fi/browser/browser/zen-vertical-tabs.ftl
  locales/fr/browser/browser/preferences/zen-preferences.ftl
  locales/fr/browser/browser/zen-vertical-tabs.ftl
  locales/ga-IE/browser/browser/zen-folders.ftl
  locales/ga-IE/browser/browser/zen-vertical-tabs.ftl
  locales/he/browser/browser/zen-vertical-tabs.ftl
  locales/hu/browser/browser/zen-vertical-tabs.ftl
  locales/id/browser/browser/zen-vertical-tabs.ftl
  locales/is/browser/browser/zen-vertical-tabs.ftl
  locales/it/browser/browser/zen-vertical-tabs.ftl
  locales/ja/browser/browser/zen-vertical-tabs.ftl
  locales/ko/browser/browser/zen-vertical-tabs.ftl
  locales/lt/browser/browser/zen-vertical-tabs.ftl
  locales/nl/browser/browser/zen-vertical-tabs.ftl
  locales/nn-NO/browser/browser/zen-vertical-tabs.ftl
  locales/pl/browser/browser/zen-vertical-tabs.ftl
  locales/pt-BR/browser/browser/zen-vertical-tabs.ftl
  locales/pt-PT/browser/browser/zen-vertical-tabs.ftl
  locales/ru/browser/browser/zen-vertical-tabs.ftl
  locales/sv-SE/browser/browser/zen-vertical-tabs.ftl
  locales/th/browser/browser/zen-vertical-tabs.ftl
  locales/tr/browser/browser/zen-vertical-tabs.ftl
  locales/uk/browser/browser/zen-vertical-tabs.ftl
  locales/vi/browser/browser/preferences/zen-preferences.ftl
  locales/vi/browser/browser/zen-folders.ftl
  locales/vi/browser/browser/zen-vertical-tabs.ftl
  locales/vi/browser/browser/zen-workspaces.ftl
  locales/zh-CN/browser/browser/zen-vertical-tabs.ftl
  locales/zh-TW/browser/browser/zen-vertical-tabs.ftl
Labels: Improvement, size:M

#10111 fix: adds translation for the 'new folder' feat in Portuguese language
  locales/pt-BR/browser/browser/zen-vertical-tabs.ftl
  locales/pt-PT/browser/browser/zen-vertical-tabs.ftl
Labels: size:XS, lgtm

#10147 fix: make folder search input take up full width
  src/browser/base/content/zen-panels/folders-search.inc
  src/zen/folders/zen-folders.css
Labels: size:XS, lgtm

#10159 New Crowdin updates
  locales/ar/browser/browser/zen-folders.ftl
  locales/ca/browser/browser/zen-folders.ftl
  locales/cs/browser/browser/zen-folders.ftl
  locales/cy/browser/browser/zen-folders.ftl
  locales/da/browser/browser/zen-folders.ftl
  locales/de/browser/browser/zen-folders.ftl
  locales/el/browser/browser/zen-folders.ftl
  locales/en-GB/browser/browser/zen-folders.ftl
  locales/es-ES/browser/browser/zen-folders.ftl
  locales/et/browser/browser/zen-folders.ftl
  locales/fa/browser/browser/zen-folders.ftl
  locales/fi/browser/browser/zen-folders.ftl
  locales/fr/browser/browser/zen-folders.ftl
  locales/ga-IE/browser/browser/zen-folders.ftl
  locales/he/browser/browser/zen-folders.ftl
  locales/hu/browser/browser/zen-folders.ftl
  locales/id/browser/browser/zen-folders.ftl
  locales/is/browser/browser/zen-folders.ftl
  locales/it/browser/browser/zen-folders.ftl
  locales/ja/browser/browser/zen-folders.ftl
  locales/ko/browser/browser/zen-folders.ftl
  locales/lt/browser/browser/zen-folders.ftl
  locales/nl/browser/browser/zen-folders.ftl
  locales/nn-NO/browser/browser/zen-folders.ftl
  locales/pl/browser/browser/zen-folders.ftl
  locales/pt-BR/browser/browser/zen-folders.ftl
  locales/pt-PT/browser/browser/zen-folders.ftl
  locales/ru/browser/browser/zen-folders.ftl
  locales/sv-SE/browser/browser/zen-folders.ftl
  locales/th/browser/browser/zen-folders.ftl
  locales/tr/browser/browser/zen-folders.ftl
  locales/uk/browser/browser/zen-folders.ftl
  locales/vi/browser/browser/zen-folders.ftl
  locales/zh-CN/browser/browser/zen-folders.ftl
  locales/zh-TW/browser/browser/zen-folders.ftl
Labels: size:M

#10174 New Crowdin updates
  locales/ca/browser/browser/zen-folders.ftl
  locales/ca/browser/browser/zen-vertical-tabs.ftl
  locales/da/browser/browser/zen-folders.ftl
  locales/da/browser/browser/zen-vertical-tabs.ftl
  locales/de/browser/browser/zen-folders.ftl
  locales/es-ES/browser/browser/zen-folders.ftl
  locales/et/browser/browser/zen-folders.ftl
  locales/fr/browser/browser/zen-folders.ftl
  locales/hu/browser/browser/zen-folders.ftl
  locales/ko/browser/browser/zen-folders.ftl
  locales/ko/browser/browser/zen-vertical-tabs.ftl
  locales/uk/browser/browser/zen-folders.ftl
  locales/uk/browser/browser/zen-vertical-tabs.ftl
Labels: Improvement, size:M
